name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies and package application
      run: |
        pip install -r requirements.txt -t lib
        cd lib
        zip -r9 ../deployment_package.zip .
        cd ..
        zip -g deployment_package.zip lambda_function.py
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

    - name: Deploy to AWS Lambda
      run: |
          aws lambda update-function-code --function-name ai-resume-gpt --zip-file fileb://deployment_package.zip


