name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies and package application
      run: |
        pip install -r requirements.txt -t lib
        cd lib
        zip -r9 ../deployment_package.zip .
        cd ..
        zip -g deployment_package.zip lambda_function.py


